In [2]:
from sklearn import datasets

In [3]:
iris = datasets.load_iris()
type(iris)

sklearn.utils.Bunch

In [4]:
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [ ]:
x=iris.data
y=iris.target
x.shape, y.shape, type(x), type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [5]:
print('Hello')

Hello


In [ ]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [ ]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [ ]:
log.fit(x_train, y_train)

LogisticRegression()

In [ ]:
log.coef_, log.intercept_

(array([[-0.44244824,  0.8349307 , -2.32456997, -0.98559749],
        [ 0.48315234, -0.37810124, -0.22978143, -0.76469348],
        [-0.0407041 , -0.45682946,  2.55435139,  1.75029097]]),
 array([  9.53729246,   2.41508418, -11.95237664]))

In [ ]:
log.predict_proba(x_train[100:104])

array([[9.68547826e-03, 8.46895175e-01, 1.43419347e-01],
       [7.58935308e-05, 1.10097841e-01, 8.89826266e-01],
       [9.71206149e-01, 2.87937683e-02, 8.30689744e-08],
       [8.10307230e-04, 2.62551250e-01, 7.36638443e-01]])

In [ ]:
log.predict(x_train[100:104])

array([1, 2, 0, 2])

In [ ]:
y_train

array([0, 0, 2, 1, 0, 2, 2, 2, 1, 0, 2, 2, 2, 2, 2, 0, 0, 2, 1, 2, 0, 1,
       1, 1, 0, 2, 0, 1, 1, 1, 1, 1, 0, 2, 0, 0, 2, 2, 2, 0, 2, 2, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 2, 0, 2, 1, 2, 1, 2, 0, 0,
       1, 1, 1, 2, 0, 1, 0, 2, 0, 0, 0, 1, 2, 0, 2, 2, 2, 0, 1, 1, 1, 0,
       2, 0, 1, 0, 1, 0, 2, 1, 1, 1, 0, 1, 1, 2, 0, 2, 2, 1, 2, 2, 1, 2,
       0, 2])

In [ ]:
y_prod

NameError: name 'y_prod' is not defined